CREATE DATABASE [Final2Jce]
USE [Master]
GO
CREATE LOGIN [usr2dains] WITH PASSWORD=N'12345678',
	DEFAULT_DATABASE=[Final2Jce],
	CHECK_EXPIRATION=OFF,
	CHECK_POLICY=ON
GO
USE [Final2Jce]
GO 
CREATE USER [usr2dains] FOR LOGIN [usr2dains]
GO
ALTER ROLE [db_owner] ADD MEMBER [usr2dains]
GO